name: Build and Deploy
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4 # https://github.com/marketplace/actions/deploy-to-github-pages
        with:
          branch: gh-pages
          folder: dist
